### ISSUE TITLE
About the results in Table 2

### ISSUE THREAD

**Issue by wuhaoxz** [NineAbyss/ZeroG#1]
Dear authors,

This is a great piece of work. However, I encountered some issues:
1. When I attempted to reproduce the results in your Table 2 using the command
`python code/main_TextBP_benchmark.py --dataset Arxiv Citeseer Pubmed --test_dataset Cora --k 2 --if_norm --device 2 --epoch 3`
the result I obtained for Cora was 57.35, which is significantly lower than the reported result of 68.72. I tried adjusting the value of k, but the improvement was negligible. Could you please provide the hyperparameter configuration or the running script to reproduce the experimental results in your Table 2?
2. Could you approve my request for access to the P-Home and P-Tech datasets?
Thank you very much!

**Comment by NineAbyss** [comment]
Thanks for your interests in our work!
1. I have run the same command 
```
python code/main_TextBP_benchmark.py --dataset Arxiv Citeseer Pubmed --test_dataset Cora --k 2 --if_norm --device 2 --epoch 3
```
and after the first epoch, the acc for Cora is 64.22.
<img width="997" alt="截屏2024-07-07 17 12 17" src="https://github.com/NineAbyss/ZeroG/assets/113831700/b2d22541-e738-4106-8738-22bd5637740c">
Maybe you can share your training log with me then we can figure it out together.
2. Yes, I have changed the authority of the dataset, now you can access them. Sorry for the confusion.
