### ISSUE TITLE
Missing “model.py” file and “class TextModel”

### ISSUE THREAD

**Issue by easyduo2** [NineAbyss/ZeroG#2]
[2024-08-07 17:35:21,530] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
DGL backend not selected or invalid.  Assuming PyTorch for now.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
[93m [WARNING] [0m using untested triton version (2.1.0), only 1.0.0 is known to be compatible
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
Traceback (most recent call last):
  File "/gemini/code/ZeroG/code/main_TextBP_benchmark.py", line 4, in <module>
    from dataset_benchmark import load_dataset
  File "/gemini/code/ZeroG/code/dataset_benchmark.py", line 18, in <module>
    from model import TextModel
ModuleNotFoundError: No module named 'model'

**Comment by NineAbyss** [comment]
> [2024-08-07 17:35:21,530] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect) DGL backend not selected or invalid. Assuming PyTorch for now. �[93m [WARNING] �[0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH �[93m [WARNING] �[0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1 �[93m [WARNING] �[0m using untested triton version (2.1.0), only 1.0.0 is known to be compatible Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable. Valid options are: pytorch, mxnet, tensorflow (all lowercase) Traceback (most recent call last): File "/gemini/code/ZeroG/code/main_TextBP_benchmark.py", line 4, in from dataset_benchmark import load_dataset File "/gemini/code/ZeroG/code/dataset_benchmark.py", line 18, in from model import TextModel ModuleNotFoundError: No module named 'model'

We fix this by uploading `model.py`. Thank you!
